version: '3'

services:
  chainmainnode0:
    container_name: chainmainnode0
    image: "cryptocom/chainmaindnode"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-chain-maind.log}
    volumes:
      - ${BUILDDIR:-./build}:/chain-maind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  chainmainnode1:
    container_name: chainmainnode1
    image: "cryptocom/chainmaindnode"
    ports:
      - "26659-26660:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-chain-maind.log}
    volumes:
      - ${BUILDDIR:-./build}:/chain-maind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  chainmainnode2:
    container_name: chainmainnode2
    image: "cryptocom/chainmaindnode"
    environment:
      - ID=2
      - LOG=${LOG:-chain-maind.log}
    ports:
      - "26661-26662:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ${BUILDDIR:-./build}:/chain-maind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  chainmainnode3:
    container_name: chainmainnode3
    image: "cryptocom/chainmaindnode"
    environment:
      - ID=3
      - LOG=${LOG:-chain-maind.log}
    ports:
      - "26663-26664:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ${BUILDDIR:-./build}:/chain-maind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
