slashingtest:
  validators:
    - coins: 40cro
      staked: 40cro
    - coins: 10cro
      staked: 10cro
    - coins: 10cro
      staked: 10cro
  accounts:
    - name: community
      coins: 100cro
    - name: ecosystem
      coins: 200cro
    - name: reserve
      coins: 200cro
      vesting: "60s"
    - name: launch
      coins: 100cro
  genesis:
   app_state:
     staking:
       params:
         unbonding_time: "10s"
     slashing:
       params:
         signed_blocks_window: "10"
         slash_fraction_downtime: "0.01"
         downtime_jail_duration: "60s"
